
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejsapp
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 7000  
      nodePort: 32766
  type: LoadBalancer  
    