apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  labels:
    app: nodejsapp
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodeserver
        image: pennmokom/kubsample3:latest  # Specify your Node.js image version
        ports:
        - containerPort: 7000  # Port the app runs on

       