name: Build and Push Docker Image

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main  # Change 'main' to the branch name you want to track

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub using the stored secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-nodejs-app:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-nodejs-app:latest
